# Generated by Django 4.0 on 2021-12-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=2000)),
                ('salary', models.FloatField()),
                ('required_skills', models.ManyToManyField(to='skills.SkillModel')),
            ],
        ),
    ]
