# Generated by Django 4.0 on 2021-12-19 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField(max_length=3000)),
                ('birth_date', models.DateField()),
                ('recruiter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruiters.recruitermodel')),
                ('skills', models.ManyToManyField(to='skills.SkillModel')),
            ],
        ),
    ]
