# Generated by Django 4.0 on 2021-12-19 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatemodel',
            name='recruiter',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='recruiters.recruitermodel'),
        ),
    ]
